version: "3.8"

services:
  mysql:
    image: mysql:8.1
    container_name: ebooth_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7788
      MYSQL_DATABASE: ebooth_db
      MYSQL_USER: ebooth_db
      MYSQL_PASSWORD: 7788
    ports:
      - "3388:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
