name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=2048"

      - name: Archive production build
        run: |
          tar -czf build.tar.gz .next public package.json next.config.mjs

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 185.84.160.236 >> ~/.ssh/known_hosts

      - name: Upload build to VPS
        run: |
          scp build.tar.gz xver@185.84.160.236:/home/xver/eBooth/ebooth-gamifications/

      - name: Extract and restart on VPS
        run: |
          ssh xver@185.84.160.236 "
            cd /home/xver/eBooth/ebooth-gamifications &&
            tar -xzf build.tar.gz &&
            rm -f build.tar.gz &&
            npm install --omit=dev &&
            /home/xver/.nvm/versions/node/v22.16.0/bin/pm2 restart 'ebooth' || /home/xver/.nvm/versions/node/v22.16.0/bin/pm2 start npm --name 'ebooth' -- run start
          "
